
export const GET_LABCART_LOADING = "GET_LABCART_LOADING";
export const GET_LABCART_SUCCESS = "GET_LABCART_SUCCESS";
export const GET_LABCART_ERROR = "GET_LABCART_ERROR";

export const POST_LABCART_LOADING = "POST_LABCART_LOADING";
export const POST_LABCART_SUCCESS = "POST_LABCART_SUCCESS";
export const POST_LABCART_ERROR = "POST_LABCART_ERROR";

export const DELETE_LABCART_LOADING = "DELETE_LABCART_LOADING";
export const DELETE_LABCART_SUCCESS = "DELETE_LABCART_SUCCESS";
export const DELETE_LABCART_ERROR = "DELETE_LABCART_ERROR";

export const UPDATE_LABCART_LOADING = "UPDATE_LABCART_LOADING";
export const UPDATE_LABCART_SUCCESS = "UPDATE_LABCART_SUCCESS";
export const UPDATE_LABCART_ERROR = "UPDATE_LABCART_ERROR";

export const TEST_BOOKING_LOADING = "TEST_BOOKING_LOADING";
export const TEST_BOOKING_SUCCESS = "TEST_BOOKING_SUCCESS";
export const TEST_BOOKING_ERROR = "TEST_BOOKING_ERROR";